# Site settings
title: A site for Mathew
description: A blog about coding in the open source
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mathew May
user_description: Experienced Web Developer with a demonstrated history of working in the education management industry. Skilled in Moodle, PHP, HTML and other frameworks. Strong education professional with a Bachelor's degree focused in Information Technology.
user_title: eLearning Software Developer
email: mathewm@hotmail.co.nz
# twitter_username: lorem_ipsum
github_username:  chocolate-lightning
moodle_userid:  2170787

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
