# Site settings
title: A site for Mathew
description: A blog about coding in the open source
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mathew May
user_description: Some description about myself
user_title: eLearning Software Developer
email: mathewm@hotmail.co.nz
# twitter_username: lorem_ipsum
github_username:  chocolate-lightning
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
